# Имя выходного файла Excel
outfile: "bonds_today.xlsx"

# true — выгружать весь справочник, false — только базовые инструменты
all: false

# Фильтры (можно оставить null)
# min_ytm: 12.0        # минимальная YTM, % годовых (например 12.0). null — без фильтра
# max_duration: 3.0    # максимальная "дюрация" (лет до погашения). null — без фильтра

# # Список ISIN (если указать — выгрузится только он; можно оставить пустым)
# only_isins:
#   - "RU000A10B4T4"
#   - "RU000A105GE2"
#   - "RU000A0ZYR91"
#   - "RU000A0ZYX28"